# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StoryMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 5.0.0'
  pod 'RealmSwift', '~> 10'

end
