# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StoryMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # ignore all warnings from all pods
  inhibit_all_warnings!

  pod 'SnapKit', '~> 5.0.0'
  pod 'RealmSwift', '~> 10'
	pod 'Alamofire', '~> 5.4'

end

target 'StoryMapTests' do
  
  use_frameworks!
  
  pod 'EarlGreyTest'
  
end
